name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push: 
    paths: 
      - "backend/**"
    branches:
      - "main"



jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - uses: actions/setup-node@v3 
        with:
          node-version: '14'
      - run: node "backend/app.js"  
        env: 
          DBNAME: "sbtphcsd"
          DBHOST: "localhost"
